package com.pesky.app.navigation

import androidx.compose.animation.*
import androidx.compose.animation.core.tween
import androidx.compose.runtime.*
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.navArgument
import com.pesky.app.ui.animations.PeskyAnimations
import com.pesky.app.ui.screens.*

/**
 * Navigation routes for the app.
 */
sealed class Screen(val route: String) {
    object Login : Screen("login")
    object CreateDatabase : Screen("create_database")
    object Vault : Screen("vault")
    object EntryDetail : Screen("entry/{entryUuid}") {
        fun createRoute(entryUuid: String) = "entry/$entryUuid"
    }
    object AddEntry : Screen("add_entry")
    object EditEntry : Screen("edit_entry/{entryUuid}") {
        fun createRoute(entryUuid: String) = "edit_entry/$entryUuid"
    }
    object Settings : Screen("settings")
}

/**
 * Main navigation host for the app.
 */
@Composable
fun PeskyNavHost(navController: NavHostController) {
    var showPasswordGenerator by remember { mutableStateOf(false) }
    var onPasswordGenerated by remember { mutableStateOf<((String) -> Unit)?>(null) }
    
    // Password generator dialog
    if (showPasswordGenerator) {
        PasswordGeneratorDialog(
            onDismiss = { showPasswordGenerator = false },
            onPasswordSelected = { password ->
                onPasswordGenerated?.invoke(password)
                showPasswordGenerator = false
            }
        )
    }
    
    NavHost(
        navController = navController,
        startDestination = Screen.Login.route,
        enterTransition = {
            slideInHorizontally(
                initialOffsetX = { it },
                animationSpec = tween(PeskyAnimations.screenTransitionDuration)
            ) + fadeIn(animationSpec = tween(PeskyAnimations.screenTransitionDuration))
        },
        exitTransition = {
            slideOutHorizontally(
                targetOffsetX = { -it / 3 },
                animationSpec = tween(PeskyAnimations.screenTransitionDuration)
            ) + fadeOut(animationSpec = tween(PeskyAnimations.screenTransitionDuration))
        },
        popEnterTransition = {
            slideInHorizontally(
                initialOffsetX = { -it / 3 },
                animationSpec = tween(PeskyAnimations.screenTransitionDuration)
            ) + fadeIn(animationSpec = tween(PeskyAnimations.screenTransitionDuration))
        },
        popExitTransition = {
            slideOutHorizontally(
                targetOffsetX = { it },
                animationSpec = tween(PeskyAnimations.screenTransitionDuration)
            ) + fadeOut(animationSpec = tween(PeskyAnimations.screenTransitionDuration))
        }
    ) {
        // Login screen
        composable(Screen.Login.route) {
            LoginScreen(
                onDatabaseOpened = {
                    navController.navigate(Screen.Vault.route) {
                        popUpTo(Screen.Login.route) { inclusive = true }
                    }
                },
                onCreateDatabase = {
                    navController.navigate(Screen.CreateDatabase.route)
                }
            )
        }
        
        // Create database screen
        composable(Screen.CreateDatabase.route) {
            CreateDatabaseScreen(
                onDatabaseCreated = {
                    navController.navigate(Screen.Vault.route) {
                        popUpTo(Screen.Login.route) { inclusive = true }
                    }
                },
                onNavigateBack = {
                    navController.popBackStack()
                }
            )
        }
        
        // Vault screen
        composable(Screen.Vault.route) {
            VaultScreen(
                onNavigateToEntry = { entryUuid ->
                    if (entryUuid != null) {
                        navController.navigate(Screen.EntryDetail.createRoute(entryUuid))
                    } else {
                        navController.navigate(Screen.AddEntry.route)
                    }
                },
                onNavigateToSettings = {
                    navController.navigate(Screen.Settings.route)
                },
                onVaultLocked = {
                    navController.navigate(Screen.Login.route) {
                        popUpTo(0) { inclusive = true }
                    }
                }
            )
        }
        
        // Entry detail screen
        composable(
            route = Screen.EntryDetail.route,
            arguments = listOf(
                navArgument("entryUuid") { type = NavType.StringType }
            )
        ) { backStackEntry ->
            val entryUuid = backStackEntry.arguments?.getString("entryUuid") ?: return@composable
            
            EntryDetailScreen(
                entryUuid = entryUuid,
                onNavigateBack = {
                    navController.popBackStack()
                },
                onEdit = { uuid ->
                    navController.navigate(Screen.EditEntry.createRoute(uuid))
                }
            )
        }
        
        // Add entry screen
        composable(Screen.AddEntry.route) {
            AddEditEntryScreen(
                entryUuid = null,
                onNavigateBack = {
                    navController.popBackStack()
                },
                onOpenGenerator = {
                    onPasswordGenerated = { password ->
                        // This will be handled by the ViewModel
                    }
                    showPasswordGenerator = true
                }
            )
        }
        
        // Edit entry screen
        composable(
            route = Screen.EditEntry.route,
            arguments = listOf(
                navArgument("entryUuid") { type = NavType.StringType }
            )
        ) { backStackEntry ->
            val entryUuid = backStackEntry.arguments?.getString("entryUuid") ?: return@composable
            
            AddEditEntryScreen(
                entryUuid = entryUuid,
                onNavigateBack = {
                    navController.popBackStack()
                },
                onOpenGenerator = {
                    onPasswordGenerated = { password ->
                        // This will be handled by the ViewModel
                    }
                    showPasswordGenerator = true
                }
            )
        }
        
        // Settings screen
        composable(Screen.Settings.route) {
            SettingsScreen(
                onNavigateBack = {
                    navController.popBackStack()
                }
            )
        }
    }
}
