package com.simpleattendance;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

public class ReportActivity extends AppCompatActivity {
    
    private TextView reportTextView;
    private Button shareButton, backButton;
    
    private String className;
    private String subjectName;
    private int presentCount;
    private int absentCount;
    private ArrayList<String> absentStudents;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_report);

        getIntentData();
        initViews();
        generateReport();
        setupClickListeners();
    }

    private void getIntentData() {
        className = getIntent().getStringExtra("CLASS_NAME");
        subjectName = getIntent().getStringExtra("SUBJECT_NAME");
        presentCount = getIntent().getIntExtra("PRESENT_COUNT", 0);
        absentCount = getIntent().getIntExtra("ABSENT_COUNT", 0);
        absentStudents = getIntent().getStringArrayListExtra("ABSENT_STUDENTS");
        
        if (absentStudents == null) {
            absentStudents = new ArrayList<>();
        }
    }

    private void initViews() {
        reportTextView = findViewById(R.id.reportTextView);
        shareButton = findViewById(R.id.shareButton);
        backButton = findViewById(R.id.backButton);
    }

    private void generateReport() {
        String reportText = generateTextReport();
        reportTextView.setText(reportText);
    }

    private void setupClickListeners() {
        shareButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                shareReport();
            }
        });

        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });
    }

    private String generateTextReport() {
        StringBuilder sb = new StringBuilder();
        sb.append("ATTENDANCE REPORT\n");
        sb.append("================\n\n");
        sb.append("Class: ").append(className != null ? className : "N/A").append("\n");
        sb.append("Subject: ").append(subjectName != null ? subjectName : "N/A").append("\n");
        sb.append("Date: ").append(new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(new Date())).append("\n");
        sb.append("Time: ").append(new SimpleDateFormat("HH:mm", Locale.getDefault()).format(new Date())).append("\n\n");
        
        int totalCount = presentCount + absentCount;
        sb.append("Total Students: ").append(totalCount).append("\n");
        sb.append("Present: ").append(presentCount).append("\n");
        sb.append("Absent: ").append(absentCount).append("\n");
        
        if (totalCount > 0) {
            double attendancePercentage = (double) presentCount / totalCount * 100;
            sb.append("Attendance %: ").append(String.format("%.1f", attendancePercentage)).append("%\n\n");
        }
        
        if (!absentStudents.isEmpty()) {
            sb.append("Absent Students:\n");
            sb.append("---------------\n");
            for (int i = 0; i < absentStudents.size(); i++) {
                sb.append((i + 1)).append(". ").append(absentStudents.get(i)).append("\n");
            }
        } else {
            sb.append("All students were present!\n");
        }
        
        sb.append("\n").append("Generated by Roll Call by PSB");
        
        return sb.toString();
    }

    private void shareReport() {
        String reportText = generateTextReport();
        
        Intent shareIntent = new Intent(Intent.ACTION_SEND);
        shareIntent.setType("text/plain");
        shareIntent.putExtra(Intent.EXTRA_TEXT, reportText);
        shareIntent.putExtra(Intent.EXTRA_SUBJECT, "Attendance Report - " + className + " - " + subjectName);
        
        try {
            startActivity(Intent.createChooser(shareIntent, "Share Attendance Report"));
        } catch (android.content.ActivityNotFoundException ex) {
            // Handle case where no app can handle the intent
            android.widget.Toast.makeText(this, "No app available to share the report", 
                android.widget.Toast.LENGTH_SHORT).show();
        }
    }
}